---
- name: Install s/w's based on OS flavour
  hosts: all
  tasks:
    - name: Install git using apt on Ubuntu servers
      apt:
        name: git
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
    - name: Install git using yum on RHEL servers
      yum:
        name: git
        state: present
        update_cache: yes
      when: ansible_distribution == "RedHat"
