---
- name: Check if a file is executable if so delete it
  hosts: all
  tasks:
    - name: Check for file1
      stat:
        path: /tmp/file1
      register: a
    - name: Display output of the above module
      debug:
        var: a
    - name: Delete if file is executable
      file:
        name: /tmp/file1
        state: absent
      when: a.stat.executable == true
